### ISSUE TITLE
Can install any alpine package 

### ISSUE THREAD

**Issue by sploit30** [termux/proot#202] opened 2021-11-18 12:25 UTC
Hello i am using proot-distro in termux also install alpine but can't install nodejs also chromium 

Here is log
```
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ pkg install proot-distro
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libtalloc ncurses-utils proot
The following NEW packages will be installed:
  libtalloc ncurses-utils proot proot-distro
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 214 kB of archives.
After this operation, 782 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.termux.org/apt/termux-main stable/main arm libtalloc arm 2.3.3 [34.1 kB]
Get:2 https://packages.termux.org/apt/termux-main stable/main arm ncurses-utils arm 6.2.20200725-6 [81.8 kB]
Get:3 https://packages.termux.org/apt/termux-main stable/main arm proot arm 5.1.107-49 [77.3 kB]
Get:4 https://packages.termux.org/apt/termux-main stable/main arm proot-distro all 2.8.0 [20.7 kB]
Fetched 214 kB in 4s (59.0 kB/s)
Selecting previously unselected package libtalloc.
(Reading database ... 4213 files and directories currently installed.)
Preparing to unpack .../libtalloc_2.3.3_arm.deb ...
Unpacking libtalloc (2.3.3) ...
Selecting previously unselected package ncurses-utils.
Preparing to unpack .../ncurses-utils_6.2.20200725-6_arm.deb ...
Unpacking ncurses-utils (6.2.20200725-6) ...
Selecting previously unselected package proot.
Preparing to unpack .../proot_5.1.107-49_arm.deb ...
Unpacking proot (5.1.107-49) ...
Selecting previously unselected package proot-distro.
Preparing to unpack .../proot-distro_2.8.0_all.deb ...
Unpacking proot-distro (2.8.0) ...
Setting up ncurses-utils (6.2.20200725-6) ...
Setting up libtalloc (2.3.3) ...
Setting up proot (5.1.107-49) ...
Setting up proot-distro (2.8.0) ...
~ $ proot-distro install alpine
[*] Installing Alpine Linux (edge)...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine'...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/dlcache'...
[*] Downloading rootfs tarball...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-100   666  100   666    0     0    507      0  0:00:01  0:00:01 --:--:--   507
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  9 2119k    9  191k    0     0  34207      0  0:0 22 2119k   22  478k    0     0  72790      0  0:0 29 2119k   29  622k    0     0  81958      0  0:0 38 2119k   38  814k    0     0  95639      0  0:0 54 2119k   54 1150k    0     0   118k      0  0:0 61 2119k   61 1294k    0     0   120k      0  0:0 63 2119k   63 1342k    0     0   110k      0  0:0 66 2119k   66 1406k    0     0   109k      0  0:0 69 2119k   69 1470k    0     0   106k      0  0:0 73 2119k   73 1566k    0     0   106k      0  0:0 77 2119k   77 1645k    0     0    98k      0  0:0 77 2119k   77 1645k    0     0  95182      0  0:0 77 2119k   77 1645k    0     0  91113      0  0:0 78 2119k   78 1661k    0     0  90821      0  0:0 88 2119k   88 1885k    0     0  97179      0  0:0 93 2119k   93 1981k    0     0  97902      0  0:0100 2119k  100 2119k    0     0   100k      0  0:00:21  0:00:21 --:--:--  143k

[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile.d/termux-proot.sh'...
[*] Writing resolv.conf file (NS 1.1.1.1/1.0.0.1)...
[*] Writing hosts file...
[*] Registering Android-specific UIDs and GIDs...
[*] Installation finished.

Now run 'proot-distro login alpine' to log in.

~ $ proot-distro login alpine
localhost:~# apk update && apk add --no-cache nmap
 && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/community >> /etc/apk/repositories && \
>   echo @edge http://nl.alpinelinux.org/alpine/ed
ge/main >> /etc/apk/repositories && \
>   apk update && \
>   apk add --no-cache \
>   chromium
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
v3.15.0_rc3-119-g60b0d8fb1c [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.15.0_rc3-134-gd0394d592b [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 15428 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
(1/9) Installing libcrypto1.1 (1.1.1l-r5)
(2/9) Installing libgcc (10.3.1_git20211027-r0)
(3/9) Installing lua5.3-libs (5.3.6-r1)
(4/9) Installing libpcap (1.10.1-r0)
(5/9) Installing pcre (8.45-r1)
(6/9) Installing libssh2 (1.10.0-r2)
(7/9) Installing libssl1.1 (1.1.1l-r5)
(8/9) Installing libstdc++ (10.3.1_git20211027-r0)
(9/9) Installing nmap (7.92-r2)
Executing busybox-1.34.0-r3.trigger
OK: 20 MiB in 20 packages
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
v3.15.0_rc3-138-g43ae720b08 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.15.0_rc3-134-gd0394d592b [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v3.15.0_rc3-134-gd0394d592b [http://nl.alpinelinux.org/alpine/edge/community]
v3.15.0_rc3-119-g60b0d8fb1c [http://nl.alpinelinux.org/alpine/edge/main]
OK: 15430 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]
localhost:~# apk add --update nodejs npm
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20191127-r7)
(2/6) Installing nghttp2-libs (1.46.0-r0)
(3/6) Installing brotli-libs (1.0.9-r5)
(4/6) Installing c-ares (1.17.2-r0)
(5/6) Installing nodejs (16.13.0-r0)
(6/6) Installing npm (8.1.3-r0)
Executing busybox-1.34.0-r3.trigger
Executing ca-certificates-20191127-r7.trigger
OK: 63 MiB in 26 packages
localhost:~# node
Segmentation fault
localhost:~# ls
localhost:~#

```

**Comment by xeffyr** [comment] 2021-11-18 12:51
Alpine Linux has chromium only for AArch64 and x86_64, so armv7 is out and you won't be able to install it. Don't forget that Alpine Linux is not affiliated with Termux or PRoot Distro in any way and provided as-is with all issues and without modifications from our side.

https://pkgs.alpinelinux.org/packages?name=chromium&branch=edge

> localhost:~# node
Segmentation fault

Take a look on PRoot issues page. That's a duplicate of https://github.com/termux/proot/issues/107.

**Closed by xeffyr** 2021-11-18 12:51 UTC

**Comment by sploit30** [comment] 2021-11-18 17:16
Thanks but now is there any way or i have to root
