### ISSUE TITLE
Proot usage problem

### ISSUE THREAD

**Issue by wangmings** [termux/proot#155] opened 2021-04-20 07:13 UTC
Why use the termux-chroot command on termux and enter pip list , there will be a stuck situation!

**Comment by Grimler91** [comment] 2021-04-20 07:42
Please provide more information. 

What output are you getting? 
What output did you expect?
How can the issue be reproduced?
What device, and android version, and termux version, and proot version, are you using?

**Comment by wangmings** [comment] 2021-04-23 10:22
Android version: 10
Termux version: 0.108

 Question:
Start the termux-chroot command!  Cause some commands to freeze!  Long execution time!

 Problem demonstration:
 1. Open Termux
 2. Enter the termux-chroot command
 3. Enter pip list

 You can see it from the above demo!
 It takes longer to start the termux-chroot command and execute the pip list command!

**Comment by Grimler91** [comment] 2021-04-23 10:44
Running commands in proot might take longer time than in a normal shell since proot adds an additional layer intercepting syscalls.

Closing as not a bug.

**Closed by Grimler91** 2021-04-23 10:44 UTC

**Comment by ZhymabekRoman** [comment] 2021-04-23 10:54
> It takes longer to start the termux-chroot command and execute the pip list command!

Command pip list even on a powerful computer solidly launches, it took me 15 seconds on my laptop. 
```
$ time pip freeze
....

real    0m16,148s
user    0m5,090s
sys     0m0,020s
```

**Comment by wangmings** [comment] 2021-04-23 18:55
Is there no solution

**Comment by ZhymabekRoman** [comment] 2021-04-24 03:56
> Is there no solution

proot has absolutely nothing to do with this problem, and this cannot be solved in any way
