### ISSUE TITLE
Port map extension

### ISSUE THREAD

**Issue by Promaethius** [termux/proot#24] opened 2018-06-24 20:07 UTC
Would it be possible to update this with the current version of PRoot which adds port forwarding extensions?

UPDATE: I really don't need this anymore. After messing around with trying to fix the portmap extension myself, I thought huh proot will host the process I need to expose in the termux userspace so if I just get my termux IP things should work and lo and behold I have a running instance of orientdb that I can develop with

**Comment by michalbednarski** [comment] 2018-06-25 17:08
This and upstream have diverged and therefore PRoot is not updated, but individual features can be ported; As you don't need port mapper anymore then I'll close this for now; If anybody else would like port map extension please comment.

**Comment by ExtremeNerd** [comment] 2018-07-05 16:02
Think port mapping option is required if possible. Because am working on Alpine Linux under PRoot and could not get network stuff work so far.

**Comment by michalbednarski** [comment] 2018-07-06 08:34
I'm currently on holiday with limited computer access so I'll be able to add this extension in next week.

That being said, `port map` is just for rewriting ports applications listen on (e.g. http server hardcoded for port 80 and not offering option to change this). What you probably need is to [configure dns server](https://github.com/Neo-Oli/termux-ubuntu/blob/c67ee04ff36e2b83156cb4e7c9b1fe01ef2b00bd/ubuntu.sh#L31).

**Comment by michalbednarski** [comment] 2018-07-14 17:32
Looks like when copying from upstream the portmap extension `--port orig_port:remapped_port` works, however `--netcoop` appears to not.

Anyway, would you like to have it included? (Although I still doubt this is what you need.)

**Comment by ExtremeNerd** [comment] 2018-07-21 01:51
I changed DNS config but network did not seem to work from within PRooted alpine linux. Don't know if it is a problem with my handset or proot or alpine linux rootfs, (latter is highly unlikely)....

On Jul 14, 2018 11:02 PM, michalbednarski <notifications@github.com> wrote:

Looks like when copying from upstream the portmap extension --port orig_port:remapped_port works, however --netcoop appears to not.

Anyway, would you like to have it included? (Although I still doubt this is what you need.)

**Comment by michalbednarski** [comment] 2018-07-21 12:19
Where did you get Alpine from? I've tried https://github.com/Hax4us/TermuxAlpine on aarch64 emulator and network works fine. What host Android and Linux (`uname -a`) do you have?

**Comment by ExtremeNerd** [comment] 2018-07-22 14:32
* from alpine official site, minimal rootfs for containers.
* armhf

On Jul 21, 2018 5:49 PM, michalbednarski <notifications@github.com> wrote:

Where did you get Alpine from? I've tried https://github.com/Hax4us/TermuxAlpine on aarch64 emulator and network works fine. What host Android and Linux (uname -a) do you have?

**Comment by michalbednarski** [comment] 2018-07-22 17:15
Still couldn't reproduce. Can you connect through ip (`wget 172.217.21.238`)? If you just run proot without chrooting into system can network be accessed (`proot wget google.com` outside chroot)? Do you access shell by directly launching `/bin/sh` from proot (as opposed to using `getty`/`ssh`/`init` or something like that)?

When I've tried it worked once `/etc/resolv.conf` was configured:
```
Welcome to Termux!
[...]
$ uname -a
Linux localhost 3.10.49-g6be2ea0 #1 SMP PREEMPT Fri Aug 28 01:11:27 IST 2015 armv7l Android
$ getprop ro.build.fingerprint
Huawei/SCL-L01/hwSCL-Q:5.1.1/HuaweiSCL-L01/C22B131:user/release-keys
$ rm -rf alpine/
$ md5sum /sdcard/Download/alpine-minirootfs-3.8.0-armhf.tar.gz 
1264be5620bf8899526fb4510191ac7e  /sdcard/Download/alpine-minirootfs-3.8.0-armhf.tar.gz
$ mkdir alpine
$ cd alpine
$ tar -xf /sdcard/Download/alpine-minirootfs-3.8.0-armhf.tar.gz 
tar: can't create node ./dev/null: Operation not permitted
$ proot -r .
proot warning: can't chdir("/data/data/com.termux/files/home/alpine/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
localhost:/$ cd /
localhost:/$ ls /
bin    dev    etc    home   lib    media  mnt    proc   root   run    sbin   srv    sys    tmp    usr    var
localhost:/$ wget google.com
wget: bad address 'google.com'
localhost:/$ echo nameserver 8.8.8.8 > /etc/resolv.conf
localhost:/$ wget google.com
Connecting to google.com (172.217.21.238:80)
Connecting to www.google.com (172.217.20.164:80)
index.html           100% |*****************************************************************************| 11226   0:00:00 ETA
localhost:/$ 

```

**Comment by Grimler91** [comment] 2021-08-10 06:37
Closing since the issue has not been updated in quite a while, leave a comment if this is still an issue

**Closed by Grimler91** 2021-08-10 06:37 UTC
