### ISSUE TITLE
Proot is faulty since the update 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/proot#150] opened 2021-02-14 22:12 UTC
Since actualize termux, proot distro and any distribution in chroot do not work, are installed but are defective / unstable, both termux version of the play store and that of the F-droid throw me the same results, what will be happening?

**Comment by WMCB-Tech** [comment] 2021-02-15 00:31
Are you talking about the issue:
https://github.com/termux/termux-app/issues/1936

Yeah i have the same issue about when extracting rootfs through proot although it should be ignored and distros works fine as expected

*Although I'm not sure on how will affect the distro itself*

**Comment by Yisus7u7** [comment] 2021-02-15 02:25
Finish analyzing the problem further, it is not proot the error, I discovered the error, it is tar, tar can not create symbolic links, so they are unstable and defective, this problem is tar, help please

**Comment by Yisus7u7** [comment] 2021-02-15 02:26
Tar when decompressing roofts has errors with symbolic links, which is done?

**Comment by WMCB-Tech** [comment] 2021-02-15 02:35
What are you using while extracting tar?

**Comment by Yisus7u7** [comment] 2021-02-15 13:47
Nothing, just andronix scripts and proot-distro installations at the time of decompressing tar roofts has errors

**Comment by WMCB-Tech** [comment] 2021-02-21 03:32
I can confirm this happens to me as well, 

![Screenshot_2021-02-21-11-32-00-38_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/65075766/108614770-6c888480-73f5-11eb-9954-87bdd898233c.jpg)

**Comment by Yisus7u7** [comment] 2021-02-21 16:18
So I need help, this problem should be tar or the termux app, help!!!

**Comment by Yisus7u7** [comment] 2021-02-24 17:44
I wonder, what will be going on, if that shouldn't happen, why termux/tar is failing with the symbolic links of the proot distro?, we need help, apart I see that I am not the only one with this problem

**Comment by michalbednarski** [comment] 2021-02-24 19:38
On my test devices problem didn't occur and creation of this issue as far as I see wasn't near proot update so I don't have solution.

In order to attempt analyze issue I'd ask for results from running

```
PROOT_VERBOSE=9 proot-distro install debian-buster >& trace.txt
```

**Comment by Yisus7u7** [comment] 2021-02-24 19:44
Hmmm, Solve the problem already with kali and Ubuntu, Ubuntu runs normal, kali too but kali won't let me give execution permissions to the files (chmod), maybe it's already a tired jahahaja situation

**Comment by radumamy** [comment] 2021-02-27 01:19
I've replaced `tar` with `bsdtar` for extracting Rootfs, seems to work.

**Comment by Yisus7u7** [comment] 2021-03-01 21:07
Lo probare...

**Comment by Grimler91** [comment] 2021-08-10 06:47
Closing since issue seem to be solved

**Closed by Grimler91** 2021-08-10 06:47 UTC
