### ISSUE TITLE
Termux-chroot not working on android 10

### ISSUE THREAD

**Issue by azadlaw11** [termux/proot#99] opened 2020-03-02 03:55 UTC
Termux-chroot in not working on android 10 
Errorr message

$ termux-chroot
proot error: execve("/usr/bin/bash"): No such file or directory
proot info: It seems that termux-exec is active and is prepending /data/data/com.termux/... to executable paths
If this is path is not available inside proot, please "unset LD_PRELOAD"
fatal error: see `proot --help`.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-24191-5NrN0v': No such file or directory

**Comment by Grimler91** [comment] 2020-03-02 06:45
Duplicate of https://github.com/termux/proot/issues/95. As mentioned in that issue edit the `termux-chroot` script and add a line `ARGS="$ARGS -b /apex:/apex"` to fix it

**Closed by Grimler91** 2020-03-02 06:45 UTC

**Comment by azadlaw11** [comment] 2020-03-02 14:48
@Grimler91  i dont know how to do it can u please explain it?

**Comment by Grimler91** [comment] 2020-03-02 16:10
I've pushed an update. Do an `pkg upgrade` in a few minutes and it will work

**Comment by azadlaw11** [comment] 2020-03-02 21:01
@Grimler91 thanks bro aprreciated.
