### ISSUE TITLE
bug: Truncate failed permission denied 

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#48] opened 2018-11-05 21:58 UTC
I would like to kindly ask The core developer of this package for help. 
If I run 64 bit ARM Linux distribution on ARM 32 bit cpu, I get The following error.
Truncatefailed, permission denied. This bug persists while using many C or C++ applications. And I do not know, if it would be possible to solve this by making somechangesto Proot, or if this bug is caused by The fact, that My Android device is not rooted, so there is no access to some protected kernel functions?
Proot is ideal project and to be honest, it mean big revolution for all visually impaired users. Because every user can use Orca screen readerwith several Linux distributionsthanks to The rermux.
But Proot is really project for experienced absolvent of informatics studies, so I can not play with it and I can not try to repair such complex error myself.
Do you think, that you could look at this bug?
Debian ARM 64 bit stable report it very often.
To test it, install espeak from Debian
sudo apt install espeak
type
espeak hello
You will get truncate failed permission denied bug. This bug can have effect on C and C++ applications stability.
Ifis it possible to analyse The reasons of this bug and if this bug can be solved with noneed to root Android device, please let Me know.

**Comment by xeffyr** [comment] 2018-11-05 22:34
> If I run 64 bit ARM Linux distribution on ARM 32 bit cpu
> This bug persists while using many C or C++ applications.

If that were a bug... Running 64 bit program on 32 bit CPU, it's unbelievable.
You probably want to say that you tried to 32bit on 64, right ?

**Comment by xeffyr** [comment] 2018-11-06 08:28
@JanuszChmiel Why you didn't mentioned before that you used QEMU for that ?

If you used qemu-user-aarch64 from my repo, I can check it. Seems more like that issue with qemu, not proot, just haven't tested it well except qemu-user-x86_64.

**Comment by JanuszChmiel** [comment] 2018-11-06 09:28
I Am very sorry, may be, that I play on professional and I Am telling 
you nonsenses.
So.
I use Termux latest stable from Google Play,
And I run Debian which have been setup to termux by using The following 
script.

https://codeload.github.com/sp4rkie/debian-on-termux/zip/master
You can try to install Espeak as test to test truncate fault permission 
denied.
You can even try it from termux by typing
pkg install espeak
May be, that problem is not related to Proot, that problem resides 
somewhere else. Thank you very much for yours cooperation.

**Comment by xeffyr** [comment] 2018-11-06 09:48
> https://codeload.github.com/sp4rkie/debian-on-termux/zip/master You can try to install Espeak as test to test truncate fault permission denied. You can even try it from termux by typing pkg install espeak

Okay, I downloaded that script. But it doesn't use QEMU. Did you modified it ? If you did, then can you post here changes ?

**Comment by JanuszChmiel** [comment] 2018-11-06 09:54
Oh it do not use Qemu? I have made my bad assumption. I must always read 
The script before making wrong decisions.

Thank you very much for yours time and help.

**Comment by xeffyr** [comment] 2018-11-06 10:12
The script has the following lines:
```
ARCHITECTURE=$(uname -m)
case $ARCHITECTURE in    # supported architectures include: armel, armhf, arm64, i386, amd64
    aarch64) ARCHITECTURE=arm64 ;;
    x86_64) ARCHITECTURE=amd64 ;;
    armv7l) ARCHITECTURE=armhf ;;
    armel|armhf|arm64|i386|amd64|mips|mips64el|mipsel|ppc64el|s390x) ;; # Officially supported Debian Stretch architectures
    *) echo "Unsupported architecture $ARCHITECTURE"; exit ;;
esac
```

\- this means it always installs correct architecture for your device, i.e. arm installs only on arm, and arm64 only on arm64 (which is aarch64). I will test this script with espeak installation so we will know what actually happens here.

Only https://github.com/xeffyr/termux-builder uses proot + qemu to run Linux chroot'ed ubuntu.

**Comment by JanuszChmiel** [comment] 2018-11-06 10:33
Dear Mr Plyush,
	Thank you very much for yours testsand for yours patience with Me.

**Comment by xeffyr** [comment] 2018-11-06 11:44
I can't reproduce your `espeak` error. But I got something different:

```
root@localhost:~# espeak
hs
shared memfd open() failed: Function not implemented
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
```

Full log you can find here: https://gist.github.com/xeffyr/6a28b9710be0edd02fe2b629aee19a90

***

From this log you can see that `espeak` tries to use shared memory and ALSA - both features that **unusable** on Android. At least in usual way.

* shared memory - *replaced on Android by Ashmem, but still available in kernel. On recent devices it will trigger seccomp. Android is not traditional Linux-based OS, regardless of have you chroot or not.*

* ALSA - *available only on few devices. Even if available, a root will be needed.*

***

Likely, that's not a proot's issue. But since that you didn't provide any logs, it is not possible to say why you have `Permission denied` instead of error shown above.

**Comment by JanuszChmiel** [comment] 2018-11-06 13:07
Yes, but fortunately Espeak can speak even if shared memory is not being 
supported. It is possible thanks to one trick.
Export PULSE_SERVER=127.0.0.1
And it is necessary to start and install Pulseaudio in Termux. By typing 
special command
pkg install pulseaudio

pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 
auth-anonymous=1

It is all. It is possible to add this to /etc/profile Bash script so 
Termux is able to listen for streams from other distribution which uses 
Proot.
It can sound unbelievable but this work and I can even use complex 
applications such as Firefox or Seamonkey and I can share system 
resources of Android with Termux and other distribution. It is even 
possible to use screen reader Orca which uses DBUS and AT-SPI.

**Comment by xeffyr** [comment] 2018-11-06 14:44
This issue is not related to https://github.com/termux/proot/issues/50 ? If related, I hope @michalbednarski will close this and #50 because it is not possible to have chroot'ed environment on typical sdcard file systems.

**Comment by xeffyr** [comment] 2018-11-10 19:39
@michalbednarski I just thought that @JanuszChmiel tried something to do on sdcard (as in https://github.com/termux/proot/issues/50). It's very easy to get `permission denied` or similar here.

I can't reproduce this on arm64 or armhf. Maybe we missed some steps, it's [very unclear](https://github.com/termux/proot/issues/48#issue-377600475) what's @JanuszChmiel actually installed and what he did to get problem.

Also, I have looked espeak's source code and I can't find any mention of `truncate` (except comments), so problem may not be related to `espeak`.

**Comment by JanuszChmiel** [comment] 2018-11-10 20:56
Yes,you have absolutely right. Error is not only specific for Espeak. 
Esepak which is The part ot Termux repository do not cause this bug.
I will try to find other C or C++ simple app which do not have something 
to do with sound servers and I will try to use Ubuntu, since 
installscript for this distro in Termux is The most simplest.
I can only confirm very important think.
All packages for Termux, which have been specially patched to support 
modified version of Libc,which is The part of Termux installation do not 
cause this problem.
I think, that those errors are causing because ofThe fact, that it is 
not standard environment. That when somebody run some Linux distribution 
in its stricly userspace mode, there will be complex programmers issues 
related to dependent C libraries. I will accept The fact, that when I 
will run those Linux distribution by using Proot, I will ignore those 
bugs, since I Am afraid, that repairing them would require many many 
hours of debugging may be even Libc library from Debian, Ubuntu, Archlinux.
And it would require core developers of all Linux deistribution to make 
many programmers condition blocks to determine if user runs only 
userspace variant of Linux or if it is full Linux distribution.
I think, that it will also depend on if many developers will officially 
support to run Linux distribution which will share its system resources 
with Android kernel. It would be too complex.
I Am glad, that I can use Orca, Seamonkey and even Firefox in Debian, 
Ubuntu and Archlinux withoutsevere dangerous system crashes.
Because I do not see at all, I do not have problems, that X session can 
not support graphics rendering and hardware acceleration.
I have also found out, that if somebody would be able to make some Xorg 
which would allow users to use Xserver without graphics driver, it would 
be The best possible scenario.
Because for visually impaired users, it would not causeproblems if 
display donot contain some graphical output.

**Comment by Grimler91** [comment] 2021-08-10 06:40
Closing since issue has not been updated in quite a while, and it seems it cannot be reproduced

**Closed by Grimler91** 2021-08-10 06:40 UTC

**Comment by Rkbeswa** [comment] 2024-05-05 04:12
I loss may 100$ termux wallet
