### ISSUE TITLE
Proot on Oreo and Pixel C

### ISSUE THREAD

**Issue by steve-j-wilcox** [termux/proot#5] opened 2017-10-16 10:53 UTC
My pixel C updated to Oreo recently and now when I try to use proof to run fedora using the brilliant https://github.com/nmilosev/termux-fedora,  I get

After updating to Oreo I get

startfedora
/usr/libexec/grepconf.sh: line 3: 32574 Bad system call (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 32586 Bad system call (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS

Also tried the Ubuntu install but that also doesn't run. Before Oreo update it was working fine so I suspect that something selinux or similar has changed in Oreo.

Any ideas?

**Comment by michalbednarski** [comment] 2017-10-16 18:16
1. Try running it with:
```bash
PROOT_NO_SECCOMP=1 startfedora
```
(This disables use of seccomp for acceleration by proot, at some point Linux kernel switched order of ptrace syscall entry event and seccomp event, which breaks this mechanism)

Let me know if it worked as this should be fixed even though above command works.

2. Another possibility (though without an easy workaround) is that target program executes some syscall that is disallowed by seccomp policy introduced in Oreo

In either case please provide `uname -a`

I'll try running termux-fedora on Oreo emulator myself when I'm back from business trip

**Comment by steve-j-wilcox** [comment] 2017-10-17 02:59
Hi thanks for the quick reply;

Unfortunately running;  PROOT_NO_SECCOMP=1 startfedora

Still results in the error;

/usr/libexec/grepconf.sh: line 3: 23432 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 23444 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS

uname -a;
Linux localhost 3.18.0-g3d6c7b39db3 #1 SMP PREEMPT Thu Aug 17 23:26:30 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

Thanks for your help

**Comment by hnmn** [comment] 2017-10-22 12:45
Note  that with Android Oreo, seccomp was been enabled with a custom policy to filter out dangerous and Iegacy system calls.  This will spike out binaries compiled with glibc as opposed to Bionic.  So GNUroot Debian (and Termux's proot) is going to stop working once you upgrade to Oreo.

**Comment by michalbednarski** [comment] 2017-10-22 13:36
I know about seccomp and I'm going to see what particular syscall(s) are problematic here and whenever they can be emulated/skipped, though currently I'm trying to get aarch64 AOSP Oreo emulator working in order to look into this.

**Comment by steve-j-wilcox** [comment] 2017-10-23 23:43
Many thanks for looking into this, greatly appreciated.

**Comment by sdrausty** [comment] 2017-10-25 04:35
This is happening at https://github.com/sdrausty/TermuxArch/issues/7 too.

> In Termux, on a fresh install of Arch proot I got this
>
>[root@localhost home]# pacman -Syu
>Bad system call
>[root@localhost home]#
>
>I'm running Android Oreo, stock Pixel²ROM, no root and stock kernel for Pixel²ROM

**Comment by michalbednarski** [comment] 2017-10-25 17:03
Initial workaround version is ready for testing:
[Source](https://github.com/termux/proot/commit/5ed0da18d9055b0428e5823d8a19ecae754fb66a)

Binary for aarch64:
[proot_5.1.106-3_aarch64.deb.zip](https://github.com/termux/proot/files/1415455/proot_5.1.106-3_aarch64.deb.zip)
```bash
unzip proot_5.1.106-3_aarch64.deb.zip
dpkg -i proot_5.1.106-3_aarch64.deb
```

Please try and say what still doesn't work, this is initial workaround version and not ready for main repository.

**Comment by steve-j-wilcox** [comment] 2017-10-26 03:24
Sorry Michael,
I've reinstalled termux so I have a clean install, installed the new proot;

unzip proot_5.1.106-3_aarch64.deb.zip
Archive:  proot_5.1.106-3_aarch64.deb.zip
extracting: proot_5.1.106-3_aarch64.deb
$ dpkg -i proot_5.1.106-3_aarch64.deb
(Reading database ... 896 files and directories currently installed.)
Preparing to unpack proot_5.1.106-3_aarch64.deb ...
Unpacking proot (5.1.106-3)  ...
Setting up proot (5.1.106-3) ...

Then installed fedora...

fedora.tar.xz                   100%[=======================================================>]  41.56M   160KB/s    in 3m 59s

2017-10-26 14:12:51 (178 KB/s) - ‘fedora.tar.xz’ saved [43574692/43574692]

1496997fd2c357a0b876f397f5f5a63d9d027648d9055f329889de025d014f7c/layer.tar
All done! Start Fedora with 'startfedora'. Gets update with regular 'dnf update'.

But this still gives a bad system call.

$ startfedora
/usr/libexec/grepconf.sh: line 3: 17821 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 17833 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
[termux@fedora home]$

uname -a
Linux localhost 3.18.0-g3d6c7b39db3 #1 SMP PREEMPT Thu Aug 17 23:26:30 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

If you need more info please let me know

**Comment by czenzel** [comment] 2017-10-28 00:55
I am also having the issue updating packages with Pacman on Arch Linux using Termux. Pixel XL 2 with Oreo. It is reproducable on my Pixel C also. I get a bad system call. My Pixel XL 2 kernel is:

Linux localhost 4.4.56-g845c8307ee66 #1 SMP PREEMPT Tue Aug 29 04:45:06 UTC 2017 aarch64 GNU/Linux

**Comment by czenzel** [comment] 2017-10-28 00:56
I also updated to the experimental package attached to this thread. Sorry for double post.

**Comment by michalbednarski** [comment] 2017-10-28 19:21
I'm testing on emulator with Linux 3.10 and Android 7.1 (with seccomp filters imported from 8.0) so my test environment may be different.

Anyway I've got new version to try out (built from commit e2e23dd883842a0397898f62f2bf6bc56582b2e1)
[proot_5.1.106-3_aarch64_e2e23d.deb.zip](https://github.com/termux/proot/files/1424539/proot_5.1.106-3_aarch64_e2e23d.deb.zip)

Please try again and if something is still wrong please run
```
echo 'ls' | PROOT_VERBOSE=9 startfedora > log.txt 2>&1
```
(substitute `ls` with problematic command (through during tests I've seen `ls` to be enough), and provide log.txt)

**Comment by czenzel** [comment] 2017-10-28 22:16
Hi @michalbednarski Thanks for working on this. I will try it tonight and get some feedback to you!

**Comment by steve-j-wilcox** [comment] 2017-10-29 10:15
Initial install seems to work. Will try running some fedora commands to see what happens.

Many thanks,
Steve

**Comment by steve-j-wilcox** [comment] 2017-10-29 23:11
It is a big step forward, but when prooted into fedora and trying to run, for example, dnf install python3-scipy sometimes the command will start to download files, sometimes just stop. There are no error messages displayed. 

I attach the log file as outlined above (though not sure this is the correct way to show any error).

Regards,
Steve
[log.txt](https://github.com/termux/proot/files/1425578/log.txt)

**Comment by sdrausty** [comment] 2017-10-30 00:53
@steve-j-wilcox and @czenzel I notice your `uname` outputs  "aarch64 GNU/Linux". Are you on Android or on Chromebook? It's supposed to say "Android" if you're running Android, right? Of is this a new behavior for Android?

Either way I would like to know if you are using Android or Chromebook. This information will be helpful with system detection when setting up Linux in Termux.

**Comment by steve-j-wilcox** [comment] 2017-10-30 11:03
I am on android. It's a Pixel C with stock android 8.0.

**Comment by michalbednarski** [comment] 2017-10-30 21:16
@steve-j-wilcox 
`dnf install python3-scipy` appears to be working on emulator

> I also attach the log file as outlined above 

This is log for `ls` command, put tested command in echo e.g.
```
echo 'dnf install -y python3-scipy' | PROOT_VERBOSE=9 startfedora > log.txt 2>&1
```
(Pipe into `startfedora` goes into `bash` inside chroot)

---

> (though not sure this is the correct way to show any error). Is the a better way from inside the chroot?

# If you mean that you'd like to use interactive session
```
script transcript-file.txt
PROOT_VERBOSE=9 startfedora
```
(when you're done Ctrl-D until `Script done, file is ...` is shown)


# If you're interested in "better" log.txt

I'll be able to say if log is useful for me when I see it (for right command)

Above version shows strace-like report of syscalls intercepted by proot, which is the one I usually try first to diagnose problem.

For those interested, the other ones I use are (maybe I'll ask for one of them when I see log):
- using strace inside proot (just use strace as usual inside prooted environment; however this will affect execution of target program as proot will disable seccomp optimizations and will handle `execve` differently, mostly useful for analyzing what target program is doing (as opposed to what proot itself is doing))
- using strace on proot (edit `startfedora` script to include `exec` keyword before command and run `PROOT_VERBOSE=9 strace -o trace.txt startfedora`, in that case I usually need both output of strace and proot logging, in order to match trace to what proot is doing and because strace doesn't show contents of child registers accessed)

**Comment by steve-j-wilcox** [comment] 2017-11-01 10:07
Hopefully I have done this right, let me know what I need to do.

Thanks for all your help :-)
[transcript-file.txt](https://github.com/termux/proot/files/1433749/transcript-file.txt)

**Comment by tpoindex** [comment] 2017-11-01 22:03
Just to add a data point, I installed the proot from above (e2e23d) on an original Pixel with up-to-date Oreo 8.0.0.  I was finally able to run binaries in the Ubuntu chroot/proot environment (from Neo-Oli/termux-ubuntu) without getting the "Bad system call" error.  Minimal testing so far (ls, dpkg, a few other commands) but looking good so far.

**Comment by tpoindex** [comment] 2017-11-02 04:42
I did run into a problem in proot (e2e23d), using https://github.com/Neo-Oli/termux-ubuntu.  After starting the ubuntu proot environment, I ran `apt update`

and received: 

`./tracee/event.c:510: int handle_tracee_event(Tracee *, int): assertion "IS_IN_SYSENTER(tracee)" failed
proot warning: signal 6 received from process 30103`

log.txt is attached from running: `echo 'apt update' | PROOT_VERBOSE=9 ./start.sh > log.txt 2>&1`
[log.txt](https://github.com/termux/proot/files/1436481/log.txt)

Here are the device details, from uname -a and termux-info:
````
Linux localhost 3.18.52-g99dda0323132 #1 SMP PREEMPT Fri Aug 18 00:56:04 UTC 2017 aarch64 Android

Termux version:
<=0.48
Installed Termux apps:
Updatable packages:
proot/stable 5.1.106-3 aarch64 [upgradable from: 5.1.106-3]
System information:
Linux localhost 3.18.52-g99dda0323132 #1 SMP PREEMPT Fri Aug 18 00:56:04 UTC 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
Google
Device model:
Pixel
````

**Comment by michalbednarski** [comment] 2017-11-02 19:27
I think I'll need full strace of proot to figure this out

# For termux-ubuntu
(`start.sh` already has `exec`, so no patching is necessary)
```
echo 'apt update' | PROOT_VERBOSE=9 strace -o trace.txt -s5000 ./start.sh > log.txt 2>&1
```

# For termux-fedora
First, modify startfedora script to include `exec` keyword before command
```diff
--- startfedora
+++ startfedora
@@ -1,2 +1,2 @@
 #!/data/data/com.termux/files/usr/bin/bash
-proot --link2symlink -0 -r ~/fedora -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="screen-256color" PS1='[termux@fedora \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login
+exec proot --link2symlink -0 -r ~/fedora -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="screen-256color" PS1='[termux@fedora \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login
```

Then run
```
echo 'dnf install -y python3-scipy' | PROOT_VERBOSE=9 strace -o trace.txt -s5000 startfedora2 > log.txt 2>&1
```

---

I've also found another bug breaking `bash` in `termux-ubuntu` on emulator, though it appears to be unrelated to this one (I'll be fixing that too, but have to figure out what's the best way to block signals when proot injects (a.k.a. chains as it is referred to in source) additional syscalls)

Also, you might try using `PROOT_NO_SECCOMP=1` as described in my first comment on newer version, though I don't know if it'll make difference here either.

**Comment by sdrausty** [comment] 2017-11-02 21:54
Using `unset LD_PRELOAD` fixed a termux-exec issue https://github.com/sdrausty/TermuxArch/commit/71f2b4fa72a45c51d812e7598856d1ab6a2d531b maybe it will help with this one. I don't have a Pixel to check this out.

**Comment by tpoindex** [comment] 2017-11-03 02:32
Here's the results from `echo 'apt update' | PROOT_VERBOSE=9 strace -o trace.txt -s5000 ./start.sh > log.txt 2>&1`
[log.txt.gz](https://github.com/termux/proot/files/1439927/log.txt.gz)
[trace.txt.gz](https://github.com/termux/proot/files/1439928/trace.txt.gz)


and also with `echo 'apt update' |  PROOT_NO_SECCOMP=1 PROOT_VERBOSE=9 strace -o no_seccomp_trace.txt -s5000 ./start.sh > no_seccomp_log.txt 2>&1`
This resulted in a seg fault.
[no_seccomp_log.txt.gz](https://github.com/termux/proot/files/1439930/no_seccomp_log.txt.gz)
[no_seccomp_trace.txt.gz](https://github.com/termux/proot/files/1439931/no_seccomp_trace.txt.gz)

**Comment by michalbednarski** [comment] 2017-11-04 14:51
Another version to try out is ready (built from b41e439, hopefully fixes issue)
[proot_5.1.106-3_aarch64_b41e439.deb.zip](https://github.com/termux/proot/files/1443262/proot_5.1.106-3_aarch64_b41e439.deb.zip)

**Comment by steve-j-wilcox** [comment] 2017-11-06 00:57
Sorry been away over the weekend. Seems to get further, but crashed out of the chroot to termux when I tried to install without a trace on. Attached is the trace from running the above.
[log.txt](https://github.com/termux/proot/files/1444622/log.txt)

**Comment by tpoindex** [comment] 2017-11-06 01:10
This version works so far on Pixel phone. I can run 'apt update' in the
ubuntu environment.  I will continue testing.
Thanks.

**Comment by steve-j-wilcox** [comment] 2017-11-06 10:43
Running dnf update;

Upgrading        : systemd-233-7.fc26.aarch64                                                              58/184
  Running scriptlet: systemd-233-7.fc26.aarch64                                                              58/184
./path/proc.c:52: Action readlink_proc(const Tracee *, char *, const char *, const char *, Comparison): assertion "comparison == compare_paths("/proc", base)" failed
proot warning: signal 6 received from process 10796

Trying to dnf install python3-scipy wont work until update completes

**Comment by michalbednarski** [comment] 2017-11-12 09:37
I was unable to reproduce `readlink_proc` issue myself, however discussion on termux/termux-packages#1679 suggests that simply commenting out that assertion appears to work (and I doubt prooted applications will need `/proc/device-tree`, so I think that's okay for now)

[proot_5.1.106-3_aarch64_16a618.deb.zip](https://github.com/termux/proot/files/1464479/proot_5.1.106-3_aarch64_16a618.deb.zip)

**Comment by steve-j-wilcox** [comment] 2017-11-15 04:38
Interestingly ubuntu seems to work fine, updates install along with new packages, so have switched distributions for the time being. Fedora will now update but then will not install new packages due to a pid lock error. I need to go back and implement some changes identified above to the way Fedora is started as I have clean installed a number of time to make sure I wasn't messing things up :-(

**Comment by michalbednarski** [comment] 2018-02-16 19:07
Fix was implemented some time ago and there was no activity in this issue for some time, I guess I can close it

**Closed by michalbednarski** 2018-02-16 19:07 UTC
